apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "8080"
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.container.http.port }}
    - name: "8443"
      port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.container.https.port }}
  selector:
    com.bhn.service: keycloak